configMapGenerator:
- files:
  - application.yml
  name: 82023052-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ceappacr.azurecr.io/82023052
  newTag: "202410281105"
- name: cepgstapacr.azurecr.io/82023052
  newTag: "202410280727"
